name: Build and deploy Styleguide to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        with:
          jekyll_src: ''
          token: ${{ secrets.JEKYLL_PAT }}
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        with:
          jekyll_src: 'src'
          token: ${{ secrets.JEKYLL_PAT }}
